### ISSUE TITLE
undefined symbol: lua_settop

### ISSUE THREAD

**Issue by swardana** [keplerproject/md5#12]
Hello,

Currently I'm trying to setup cgit to use libravatar using lua script and one of the dependency is this lua md5. However, when I used it with my cgit instance I got error:
```
fatal: Lua error in /usr/local/lib64/cgit/filters/email-libravatar-korg.lua: error loading module 'md5.core' from file '/usr/local/lib64/lua/5.1/md5/core.so':
	/usr/local/lib64/lua/5.1/md5/core.so: undefined symbol: lua_settop
```

Below is my lua script to access the libravatar:
```
local md5 = require("md5")

function filter_open(email, page)
        buffer = ""
        hexdigest = md5.sumhexa(email:sub(2, -2):lower())
end

function filter_close()
        html("<span class='libravatar'><img class='inline' src='//seccdn.libravatar.org/avatar/" .. hexdigest .. "?s=13&d=retro' /><img class='onhover' src='//seccdn.libravatar.org/avatar/" .. hexdigest .. "?s=128&d=retro' /></span>" .. buffer)
        return 0
end

function filter_write(str)
        buffer = buffer .. str
end
```

My Lua version is 5.1.5

Please kindly help what is wrong with my setup?

Thank you.

**Comment by tomasguisasola** [comment]
He swardana

It seems your executable is not exporting the symbol correctly.  The library core.so must have access to the lua_settop which should be exported by another library or the executable.  Check how did you build those files!

Regards,
Tomás

**Comment by swardana** [comment]
Hi Tomas,

**Comment by luke727** [comment]
Was this ever resolved? I'm having the exact same issue trying to use md5 from a sysdig chislet written in lua and I have no idea how to solve it.

**Comment by luke727** [comment]
Figured it out. Sysdig is built against a newer version of lua so it wasn't exporting the same symbols. Using an older version of sysdig to work around it.
