### ISSUE TITLE
Insecure cipher warning

### ISSUE THREAD

**Issue by bbc2** [keplerproject/md5#9]
This library provides two ways to encrypt and decrypt data: one "based on MD5 and CFB" and the other one "based on DES with 56-bit keys".  MD5 is not used in any symmetric cipher commonly accepted as secure and DES has been known to be insecure since at least 2001.  While this library may still be useful for legacy reasons, would you consider adding a warning in your documentation and readme so that users don't mistakenly think this library provides them with secure ciphers?

**Comment by tomasguisasola** [comment]
I've added a note on the docs.
